### ISSUE TITLE
Issue in org-capture in your config

### ISSUE THREAD

**Issue by prashantnag** [brianmcgillion/doomd#1]
I have found one issue in your config and [report it here (https://github.com/progfolio/doct/issues/28)].
Even after the issue is resolved but` +org-capture-project-todo-file `function is not able to find the right file for todo.

**Comment by progfolio** [comment]
> `+org-capture-project-todo-file`

That's a variable, not a function. See the org-capture section of their config.org:
https://github.com/brianmcgillion/doomd/blob/master/config.org#org-capture

```emacs-lisp
    (setq +org-capture-todo-file org-default-notes-file
      +org-capture-notes-file org-default-notes-file
      +org-capture-projects-file org-default-notes-file)
```

If you don't have that variable set and you use it as the `:file` target in your template declartion you should get an error.
If the value is unbound when doct is computing the templates you should have (unless you've disabled them) received a warning:

    Warning (doct): :file +org-capture-todo-file unbound during conversion in the "Personal todo" declaration Disable showing Disable logging

If it is set to the empty string `""` it will default to the `org-default-notes-file` variable (which is what these variables are being set to in this config). That's a feature of org-capture, not doct specific.
You should be able to fix your issue by checking the value of those variables and seeing what files they point to.

**Comment by prashantnag** [comment]
@progfolio Thank you so much for your time and help. Now I got a problem with my config. as @brianmcgillion  set the variable `:function `instead of `:file` so did I. Now after setting to `:file` It is working perfectly fine.
